pipeline {
    agent any
    stages {
        stage('Login to ECR') {
            steps {
                script {
                    sh "whoami"
                    sh "helm ls"
                }
            }
        }
    }
}